#!/usr/bin/env bash
# One-command startup for the hosted solmem server.
#   ./setup.sh           plain HTTP (localhost-bound; front with your reverse proxy)
#   ./setup.sh --https   with Caddy auto-HTTPS (needs SOLMEM_DOMAIN in .env)
#
# On first run it generates a .env with secure tokens, then brings the stack up.
set -euo pipefail
cd "$(dirname "$0")"

gen() { python3 -c "import secrets; print(secrets.token_urlsafe(24))"; }

if [ ! -f .env ]; then
  echo "No .env found — generating one with secure tokens..."
  YOU=$(gen); OPS=$(gen)
  cat > .env <<EOF
# generated by setup.sh — add more devs as token=author, comma-separated
SOLMEM_TOKENS=you=$YOU
SOLMEM_ADMIN_TOKENS=ops=$OPS
SOLMEM_DOMAIN=memory.yourco.com
MISTRAL_API_KEY=
EOF
  chmod 600 .env
  echo "Wrote .env (chmod 600)."
  echo "  your token:  $YOU"
  echo "  admin token: $OPS"
  echo "Add teammates by editing SOLMEM_TOKENS in .env, then re-run."
fi

HTTPS=0
FILE="docker-compose.yml"
[ "${1:-}" = "--https" ] && { FILE="docker-compose.https.yml"; HTTPS=1; }

echo "Starting ($FILE)..."
docker compose -f "$FILE" up -d --build

# Health via the container's own healthcheck — works whether or not solmem is
# published to the host (in --https mode it sits behind Caddy, unpublished).
echo "Waiting for health..."
cid=$(docker compose -f "$FILE" ps -q solmem)
for i in $(seq 1 20); do
  status=$(docker inspect -f '{{.State.Health.Status}}' "$cid" 2>/dev/null || echo "")
  [ "$status" = "healthy" ] && { echo "solmem: healthy"; break; }
  sleep 2
done

# shellcheck disable=SC1091
set -a; . ./.env 2>/dev/null || true; set +a

echo
echo "Connect a client (use each dev's own token):"
if [ "$HTTPS" = "1" ]; then
  echo "  claude mcp add --transport http solmem https://${SOLMEM_DOMAIN:-your-domain}/mcp --header \"Authorization: Bearer <token>\""
  echo "(Caddy is issuing a cert for ${SOLMEM_DOMAIN:-your-domain}; ensure its DNS A-record points here and ports 80+443 are open.)"
else
  echo "  claude mcp add --transport http solmem http://127.0.0.1:8730/mcp --header \"Authorization: Bearer <token>\""
  echo "(localhost-bound — point your reverse proxy at 127.0.0.1:8730 for the team.)"
fi
